from __future__ import annotations

from django.db import models


class Event(models.Model):
    """
    Canonical event record generated by ingestion.

    Note: We store object_id as a string to support numeric IDs, UUIDs, etc.
    """

    actor_id = models.BigIntegerField(db_index=True)
    verb = models.CharField(max_length=64, db_index=True)

    object_type = models.CharField(max_length=64, db_index=True)
    object_id = models.CharField(max_length=128, db_index=True)

    created_at = models.DateTimeField(db_index=True)

    class Meta:
        indexes = [
            models.Index(fields=["-created_at", "-id"], name="event_created_id_desc_idx"),
            models.Index(fields=["verb", "-created_at", "-id"], name="event_verb_created_id_idx"),
            models.Index(fields=["object_id", "-created_at", "-id"], name="event_obj_created_id_idx"),
        ]


class FeedItem(models.Model):
    """
    Per-user inbox row for fast feed reads (fanout-on-write).
    """

    user_id = models.BigIntegerField(db_index=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="feed_items")

    # Copy of event.created_at for efficient ordering without a join.
    created_at = models.DateTimeField(db_index=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user_id", "event"], name="uniq_feed_user_event"),
        ]
        indexes = [
            models.Index(fields=["user_id", "-created_at", "-id"], name="feed_user_created_id_idx"),
        ]


class Notification(models.Model):
    """
    Durable notification row. SSE is best-effort; polling reads from here.
    """

    user_id = models.BigIntegerField(db_index=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="notifications")

    created_at = models.DateTimeField(db_index=True)
    read_at = models.DateTimeField(null=True, blank=True)
    delivered_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user_id", "event"], name="uniq_notif_user_event"),
        ]
        indexes = [
            models.Index(fields=["user_id", "-created_at", "-id"], name="notif_user_created_id_idx"),
        ]


class IdempotencyKey(models.Model):
    """
    Idempotency key mapping for event ingestion retries.
    """

    key = models.CharField(max_length=255, unique=True)
    event = models.ForeignKey(Event, null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        indexes = [
            models.Index(fields=["-created_at"], name="idem_created_desc_idx"),
        ]
